<?php

declare(strict_types=1);

/*
 * MichelinDevPetstore
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MichelinDevPetstoreLib;

use CoreInterfaces\Http\HttpConfigurations;
use MichelinDevPetstoreLib\Authentication\ApiKeyCredentials;
use MichelinDevPetstoreLib\Authentication\ApiKeyCredentialsBuilder;
use MichelinDevPetstoreLib\Authentication\PetstoreAuthCredentials;
use MichelinDevPetstoreLib\Authentication\PetstoreAuthCredentialsBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with PetstoreAuth
     */
    public function getPetstoreAuthCredentials(): PetstoreAuthCredentials;

    /**
     * Get the credentials builder instance to update credentials for PetstoreAuth
     */
    public function getPetstoreAuthCredentialsBuilder(): ?PetstoreAuthCredentialsBuilder;

    /**
     * Get the credentials to use with ApiKey
     */
    public function getApiKeyCredentials(): ApiKeyCredentials;

    /**
     * Get the credentials builder instance to update credentials for ApiKey
     */
    public function getApiKeyCredentialsBuilder(): ?ApiKeyCredentialsBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
